#!/bin/bash
# Overwrite pg_hba.conf with full trust auth on every connection type.
#
# Runs from /docker-entrypoint-initdb.d/ after initdb completes and before
# the upstream entrypoint starts postgres for real, so the new configuration
# applies on the post-init server start (no reload needed).
#
# WARNING: trust on every connection type. Local-only RAG sidecar — do not
# expose to any untrusted network.

set -euo pipefail

cat > "$PGDATA/pg_hba.conf" <<'HBA'
# Auto-generated by the ticket-rag postgres-pgvector image (BILL-12).
# Trust auth on every connection type. Local-only — do not expose.

# TYPE  DATABASE  USER  ADDRESS         METHOD
local   all       all                   trust
host    all       all   127.0.0.1/32    trust
host    all       all   ::1/128         trust
host    all       all   0.0.0.0/0       trust
host    all       all   ::/0            trust
HBA

echo "[ticket-rag] pg_hba.conf replaced with trust-all configuration"
